name: Routing Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Navigate to Routing Directory and Build
        working-directory: routing
        run: cargo build --verbose

      - name: Navigate to Routing Directory and Run Tests
        working-directory: routing
        run: cargo test --verbose