name: Build and Test Rust Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions/setup-rust@v2
      with:
        rust-version: stable

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
